# Generated by Django 4.1.5 on 2023-02-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_created',
            new_name='token_expired',
        ),
    ]
