# Generated by Django 4.1.5 on 2023-02-04 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AddField(
            model_name='sending',
            name='customer_lst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.customer', verbose_name='Список клиентов'),
        ),
        migrations.AddField(
            model_name='sending',
            name='finish_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='sending',
            name='sending_msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='sending',
            name='start_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='send_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время рассылки'),
        ),
    ]
