# Generated by Django 4.1.5 on 2023-02-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_attempt_options_sending_customer_lst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='customer_lst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.customer', verbose_name='Kлиенты'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='send_time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
