# Generated by Django 4.1.5 on 2023-02-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_sending_customer_lst_alter_sending_send_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'permissions': [('cancel_sending', 'Can cancel sending')]},
        ),
    ]
